#Program for simple calculator
import time

#Function to add
def add(num1,num2):
    return (num1 + num2)

#Function to subtract
def subtract(num1,num2):
    return (num1 - num2)

#Function to multiply
def multiply(num1,num2):
    return (num1 * num2)

#Function to divide
def divide(num1,num2):
    return (num1 / num2)

#Function to print selection
def display():
    print("Select Operation")
    print("===============\n"\
          "1.Addition\n"\
          "2.Subtract\n"\
          "3.Multiply\n"\
          "4.Divide\n"\
          "===============")

#Function for action
def action():
    if choice =='1':
        print(num1,'+',num2,'=',add(num1,num2))
    elif choice =='2':
        print(num1,'-',num2,'=',subtract(num1,num2))
    elif choice =='3':
        print(num1,'*',num2,'=',multiply(num1,num2))
    elif choice =='4':
        print(num1,'/',num2,'=',divide(num1,num2))
    else:
        print("Invalid Input")

display()
time.sleep(0.3)
choice=input("Enter choice(1/2/3/4): ")
time.sleep(0.2)
num1=float(input("Enter 1st number = "))
time.sleep(0.2)
num2=float(input("Enter 2nd number = "))
time.sleep(0.8)
action()
